server:
  port: 7905
eureka:
  client:
    service-url:
      # 采用curl的形式进行认证
      defaultZone: http://admin:123456@localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    # 默认使用主机名进行访问，如果想使用IP访问则启用prefer-ip-address
    prefer-ip-address: true
    # 自定义instance-id
    instance-id: ${spring.application.name}:${server.port}

spring:
  application:
    name: microservice-consumer-user-feign
logging:
  level:
    com.study.cloud.config.FeignConfiguration2: FULL
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

swagger:
  title: API示例
  desc: 基于springBoot编写的RESful-API
  version: 0.0.1.SNAPSHOT
  termsOfServiceUrl: javascript:void(0)
  license: Apache 2.0
  licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
  basePackage: com.study.cloud.microserviceconsumeruserfeign.controller
  groupName: 默认API示例分组
  contactName: wendell
  contactUrl: https://github.com/wendell-dev/restful-api-demo.git
  contactEmail: 727169395@qq.com