server:
  port: 7903
eureka:
  client:
    service-url:
      # 采用curl的形式进行认证
      defaultZone: http://admin:123456@localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    # 默认使用主机名进行访问，如果想使用IP访问则启用prefer-ip-address
    prefer-ip-address: true
    # 自定义instance-id
    instance-id: ${spring.application.name}:${spring.application.instance-id:${server.port}}

spring:
  application:
    name: consumer-user