server:
  port: 8040
eureka:
  client:
    service-url:
      # 采用curl的形式进行认证
      defaultZone: http://admin:123456@localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    # 默认使用主机名进行访问，如果想使用IP访问则启用prefer-ip-address
    prefer-ip-address: true
    # 自定义instance-id
    instance-id: ${spring.application.name}:${spring.application.instance-id:${server.port}}
spring:
  application:
    name: microservice-zuul
# zuul:
  #prefix: /wangfan
#  routes:
#    microservice-provider-user: /user/**
#    ignored-services: microservice-provider-user
#ribbon:
#  eureka:
#    enable: false
#让zuul反向代理microservice-provider-user微服务，路径是/user-path/** "abc"唯一即可
#意味着将/user-path的请求转发到microservice-provider-user服务。路由必须与一个路径
#/user-path/**可以多层匹配，但是/user-path/*只能匹配一层
#zuul:
  #routes:
  #  user:
  #    path: /user-path/**
  #    url: http://192.168.56.1:7901/


zuul:
  routes:
    abc:
      path: /user-path/**
      serviceId: microservice-provider-user
ribbon:
  eureka:
    enabled: false

microservice-provider-user:
  ribbon:
    listOfServers: http://192.168.56.1:7909
